/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinalRouteImport } from './routes/final'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretCodeRouteImport } from './routes/secret.$code'
import { Route as DecoyIdRouteImport } from './routes/decoy.$id'
import { Route as ClueIdRouteImport } from './routes/clue.$id'

const FinalRoute = FinalRouteImport.update({
  id: '/final',
  path: '/final',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretCodeRoute = SecretCodeRouteImport.update({
  id: '/secret/$code',
  path: '/secret/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DecoyIdRoute = DecoyIdRouteImport.update({
  id: '/decoy/$id',
  path: '/decoy/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClueIdRoute = ClueIdRouteImport.update({
  id: '/clue/$id',
  path: '/clue/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/clue/$id': typeof ClueIdRoute
  '/decoy/$id': typeof DecoyIdRoute
  '/secret/$code': typeof SecretCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/clue/$id': typeof ClueIdRoute
  '/decoy/$id': typeof DecoyIdRoute
  '/secret/$code': typeof SecretCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/final': typeof FinalRoute
  '/clue/$id': typeof ClueIdRoute
  '/decoy/$id': typeof DecoyIdRoute
  '/secret/$code': typeof SecretCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/final' | '/clue/$id' | '/decoy/$id' | '/secret/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/final' | '/clue/$id' | '/decoy/$id' | '/secret/$code'
  id: '__root__' | '/' | '/final' | '/clue/$id' | '/decoy/$id' | '/secret/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinalRoute: typeof FinalRoute
  ClueIdRoute: typeof ClueIdRoute
  DecoyIdRoute: typeof DecoyIdRoute
  SecretCodeRoute: typeof SecretCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/final': {
      id: '/final'
      path: '/final'
      fullPath: '/final'
      preLoaderRoute: typeof FinalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/$code': {
      id: '/secret/$code'
      path: '/secret/$code'
      fullPath: '/secret/$code'
      preLoaderRoute: typeof SecretCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoy/$id': {
      id: '/decoy/$id'
      path: '/decoy/$id'
      fullPath: '/decoy/$id'
      preLoaderRoute: typeof DecoyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clue/$id': {
      id: '/clue/$id'
      path: '/clue/$id'
      fullPath: '/clue/$id'
      preLoaderRoute: typeof ClueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinalRoute: FinalRoute,
  ClueIdRoute: ClueIdRoute,
  DecoyIdRoute: DecoyIdRoute,
  SecretCodeRoute: SecretCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
